apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-ui
  namespace: voting-app
  labels:
    app: result-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-ui
  template:
    metadata:
      labels:
        app: result-ui
    spec:
      containers:
        - name: result-ui
          image: voting/result-ui:v1.0.15
          ports:
            - containerPort: 80
