apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
  namespace: voting-app
  labels:
    app: vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
        - name: vote-ui
          image: voting/vote-ui:v1.0.19
          ports:
            - containerPort: 80
